Ortus-Solutions/ContentBox

- modules/contentbox-admin/includes/js/cb-autosave.js
- modules/contentbox-admin/includes/js/contentbox.js
- modules/contentbox-admin/includes/spacelab/css/main.css
- modules/contentbox-admin/views/_tags/content/markup.cfm
- modules/contentbox-admin/views/content/preview.cfm
- modules/contentbox-admin/views/content/simplePreview.cfm
- modules/contentbox-admin/views/contentStore/editor.cfm
- modules/contentbox-admin/views/contentStore/editorHelper.cfm
- modules/contentbox-admin/views/entries/editorHelper.cfm
- modules/contentbox-admin/views/pages/editorHelper.cfm
Updated Content Store, Blog, and Sitemap to add responsive sizing to the preview modal and added an auto save feature that will save a revision into local storage after changes are made inside the content.
>  Responsive Preview & Auto Save

- modules/contentbox-admin/includes/css/contentbox.css
Toggle state button is hided if header is too small
> Toggle state hided

- modules/contentbox-admin/views/widgets/widgetList.cfm
MOdule widget were not loaded, this should fix.
> Fix module widget not loaded

- modules/contentbox/models/modules/ModuleService.cfc
Rebuild cache when modules are activated/deactivated
> Fix CONTENTBOX-631

- modules/contentbox-admin/views/widgets/editorSelectorHelper.cfm
- modules/contentbox-admin/views/widgets/widgetList.cfm
With this commit widget panels shows pointer and are more user friendly
> Fix CONTENTBOX-644

- modules/contentbox-admin/views/menus/editor.cfm
Fix provider tooltip not displaying correctly
> Fix CONTENTBOX-650

- modules/contentbox-admin/handlers/contentStore.cfc
> Fixes MSSQL bug

- workbench/patches/3.0.0-beta/Update.cfc
> There is no property name in permission

- modules/contentbox/themes/default/Theme.cfc
- modules/contentbox/themes/default/views/_blogsidebar.cfm
Added theme settings for
* showCategoriesBlogSide
* showRecentEntriesBlogSide
* showSiteUpdatesBlogSide
* showEntryCommentsBlogSide
* showArchivesBlogSide
* showEntriesSearchBlogSide
> Feature/add theme settings gp - CONTENTBOX-654

- modules/contentbox/models/ui/ThemeService.cfc
- modules/contentbox/themes/default/Theme.cfc
Theme Settings - with fixed spacing
@lmajano
> Feature theme setting groups gp

- modules/contentbox/themes/default/Gruntfile.js
Fixed the Skin.scss copy and compilation process, including adding to the grunt watch for the skin.
> Update default theme grunt gp

- modules/contentbox-installer/layouts/simple.cfm
Allow google font request on http and https
> Fix CONTENTBOX-678

- modules/contentbox-admin/views/_tags/content/publishing.cfm
- modules/contentbox-admin/views/_tags/editors.cfm
Added JS to Publish / Draft Buttons to skip the Leave this Page warning with window.onbeforeunload
> Added JS to Publish / Draft Buttons to skip the Leave this Page

- modules/contentbox-admin/views/menus/editorHelper.cfm
Add id attribute on fresh created element, otherwise it cannot be deleted.
> Add id attribute on fresh created element

- modules/contentbox-admin/views/categories/index.cfm
- modules/contentbox-admin/views/categories/indexHelper.cfm
> Patch 704 fix category delete bug gp

- modules/contentbox-admin/views/authors/editor.cfm
- modules/contentbox-admin/views/authors/editorHelper.cfm
Add password check to authors edittor
> Fix contentbox-647

- modules/contentbox-admin/views/settings/sections/securityOptions.cfm
> Repo in SecurityOptions.cfm

- workbench/devincludes/scss/contentbox.scss
The home and fullscreen icon are not on same line. This will fix
> Fix icon postion

- modules/contentbox/models/ui/Paging.cfc
https://ortussolutions.atlassian.net/browse/CONTENTBOX-816
> Updating paging display to use maxRows instead of bandGap

- modules/contentbox-admin/views/authors/indexTable.cfm
- modules/contentbox/models/ui/Paging.cfc
https://ortussolutions.atlassian.net/browse/CONTENTBOX-817
> Correct javascript:null to void(0) for cross browser support

- modules/contentbox/models/ui/Paging.cfc
https://ortussolutions.atlassian.net/browse/CONTENTBOX-818
> Added relocation if the current page is over the total page number

- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_de_DE.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_en_US.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_es_SV.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_it_IT.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_pt_BR.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/views/home/indexHelper.cfm
https://ortussolutions.atlassian.net/browse/CONTENTBOX-819
> Added new i18n message for downloading a folder

- modules/contentbox-admin/modules/contentbox-filebrowser/views/home/index.cfm
https://ortussolutions.atlassian.net/browse/CONTENTBOX-820
> Added onContextMenu() as to file and folder to select the item

- modules/contentbox-admin/modules/contentbox-filebrowser/views/home/index.cfm
https://ortussolutions.atlassian.net/browse/CONTENTBOX-822
> Make Media Manager Location Breadcrumbs clickable

- modules/contentbox-admin/modules/contentbox-filebrowser/views/home/index.cfm
Majority of this pull is actually just formatting an if statement.
The important piece is just creating a counter for all excluded items.
https://ortussolutions.atlassian.net/browse/CONTENTBOX-823
> Adjusted Status Bar Item count for Excluded Items

- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_de_DE.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_en_US.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_es_SV.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_it_IT.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/includes/i18n/fb_pt_BR.properties
- modules/contentbox-admin/modules/contentbox-filebrowser/views/home/indexHelper.cfm
https://ortussolutions.atlassian.net/browse/CONTENTBOX-825
> Added Params for File Upload limits CONTENTBOX-825

- modules/contentbox/models/system/CBHelper.cfc
- modules/contentbox/themes/default/views/_blogIncludes.cfm
- modules/contentbox/themes/default/views/_pageIncludes.cfm
https://ortussolutions.atlassian.net/browse/CONTENTBOX-792
> 792 facebook open graph

- config/Routes.cfm
- modules/contentbox-ui/modules/contentbox-sitemap/ModuleConfig.cfc
- modules/contentbox-ui/modules/contentbox-sitemap/handlers/main.cfc
- modules/contentbox-ui/modules/contentbox-sitemap/views/sitemap_html.cfm
- modules/contentbox-ui/modules/contentbox-sitemap/views/sitemap_json.cfm
- modules/contentbox-ui/modules/contentbox-sitemap/views/sitemap_txt.cfm
- modules/contentbox-ui/modules/contentbox-sitemap/views/sitemap_xml.cfm
- modules/contentbox/models/system/CBHelper.cfc
https://ortussolutions.atlassian.net/browse/CONTENTBOX-833
> 833 google sitemap

- robots.txt
Removed crawl-delay as non respected and added exclusion for all modules directory except theme
> Better robots.txt

- modules/contentbox/themes/default/views/archives.cfm
> Update archives view to match other blog views

- modules/contentbox/modules/contentbox-admin/views/settings/rawSettingsTable.cfm
https://ortussolutions.atlassian.net/browse/CONTENTBOX-866
> Textareas in Geek Settings should be disabled

- modules/contentbox/models/ui/ThemeService.cfc
> Added flushSettingsCache to Theme load settings

- modules/contentbox/modules/contentbox-admin/views/menus/editorHelper.cfm
Remove validation from preview to avoid displaying error every time an input is filled
> Remove validation from preview

- modules/contentbox/models/content/renderers/MarkdownRenderer.cfc
had problems after updating from 2.1 to 3.5, archive link in blog lead to an exception
> thisMarkup can be Null

- modules/contentbox/models/system/CBHelper.cfc
remove CR LF TAB double space from Meta Description, Keywords etc
> Added stripWhitespace

- modules/contentbox/models/system/CBHelper.cfc
- modules/contentbox/modules/contentbox-ui/ModuleConfig.cfc
- modules/contentbox/modules/contentbox-ui/handlers/content.cfc
This allows a user to easily switch to view the site in another language
> Added __changeLang route to change fwLocale

- modules/contentbox/models/util/ForgeBoxInstaller.cfc
- modules/contentbox/modules/contentbox-admin/handlers/forgebox.cfc
- modules/contentbox/modules/contentbox-admin/handlers/modules.cfc
- modules/contentbox/modules/contentbox-admin/handlers/themes.cfc
- modules/contentbox/modules/contentbox-admin/handlers/widgets.cfc
- modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/views/home/index.cfm
Removed full file path from ForgeBox installer and media manager location bar
Prevents server paths from being exposed in the ContentBox admin
> Security updates

- modules/contentbox/models/content/BaseContent.cfc
Allows for content to be created based on URL parameters, i.e. paging
> Added query string to content cache key

- modules/contentbox/modules/contentbox-admin/views/autoupdates/check.cfm
(sorry this is just a quick browser edit, so two patches)
> Render Markdown correctly

- modules/contentbox/modules/contentbox-admin/views/forgebox/indexHelper.cfm
- modules/contentbox/modules/contentbox-admin/views/modules/indexHelper.cfm
- modules/contentbox/modules/contentbox-admin/views/themes/indexHelper.cfm
- modules/contentbox/modules/contentbox-admin/views/widgets/indexHelper.cfm
This fixes an issue with the ForgeBox installer not working when sending request as POST.
> Change $forgebox.load to GET request instead of POST

- modules/contentbox/modules/contentbox-ui/views/adminbar/index.cfm
> Make admin bar responsive

- modules/contentbox/modules/contentbox-admin/modules/contentbox-security/handlers/security.cfc
Blows up if there is an error with the 2 factor
> Incorrectly scoped variable

- modules/contentbox/modules/contentbox-admin/handlers/authors.cfc
- modules/contentbox/modules/contentbox-admin/views/authors/editor/password.cfm
- modules/contentbox/modules/contentbox-admin/views/authors/indexTable.cfm
https://ortussolutions.atlassian.net/browse/CONTENTBOX-970
> Contentbox 970 gp

- modules/contentbox/models/content/ContentService.cfc
https://ortussolutions.atlassian.net/browse/CONTENTBOX-985
> Correct the searchTerm in findPublishedContent

- modules/contentbox/models/system/CBHelper.cfc
https://ortussolutions.atlassian.net/browse/CONTENTBOX-990
> CB-990 Fix quick layout for new theme location

- modules/contentbox/models/modules/ModuleService.cfc
- modules/contentbox/models/ui/WidgetService.cfc
Fixed Issue with .listToArray and .each, not supported in CF11 @lmajano @gpickin
> Fixed Issue with .listToArray and .each, not supported in CF11

- modules/contentbox-dsncreator/views/index.cfm
> Minor typo fixes

- modules/contentbox/models/system/CBHelper.cfc
This bug prevents proper relocation from http to https and as well saving module settings didn't work
> fixing setnextevent

- modules/contentbox/modules/contentbox-admin/views/widgets/editorSelectorHelper.cfm
- modules/contentbox/widgets/Menu.cfc
> CONTENTBOX-1011 : Error while Insert Menu widget

- modules/contentbox/models/content/Category.cfc
Fix error on saving category with already used slug
> Fix unique slug category

- modules/contentbox/modules/contentbox-admin/layouts/inc/HTMLBodyEnd.cfm
Added interception point for cbadmin_beforeBodyEnd
> CONTENTBOX-1046

- modules/contentbox/models/modules/ModuleService.cfc
> Deactivate modules if its directory does not exist in disk

- modules/contentbox/models/content/BaseContent.cfc
https://ortussolutions.atlassian.net/browse/CONTENTBOX-1126
> Ensure expiration date is not required in validation rules

- modules/contentbox/modules/contentbox-admin/views/pages/indexTable.cfm
- workbench/resources/scss/theme/_panels.scss
> Fix/context menu sitemap CONTENTBOX-1157

- modules/contentbox/widgets/RecentPages.cfc
Problem with multiple select options in RecentPages widget
> CONTENTBOX-1127

- modules/contentbox/models/content/CategoryService.cfc
- modules/contentbox/widgets/RecentPages.cfc
Problem in RecentPages widget on filter by category
> CONTENTBOX-1128

- modules/contentbox/modules/contentbox-admin/layouts/admin.cfm
- workbench/package.json
- workbench/resources/js/admin.js
Removal of full screen button as all browsers support this now
> CONTENTBOX-1177

- modules/contentbox/modules/contentbox-admin/layouts/admin.cfm
- modules/contentbox/modules/contentbox-admin/views/dashboard/about.cfm
> CONTENTBOX-1159

- modules/contentbox-installer/box.json
> feat: https fix

- modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/handlers/Home.cfc
- modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/views/home/indexHelper.cfm
Fix media manager files commas in the name
> CONTENTBOX-1185

- modules/contentbox/models/system/Site.cfc
- modules/contentbox/modules/contentbox-admin/views/sites/index.cfm
Add an option to open a site from the site manager
> CONTENTBOX-1232 #testing

- modules/contentbox/modules/contentbox-admin/modules/contentbox-security/handlers/security.cfc
- modules/contentbox/modules/contentbox-admin/modules/contentbox-security/views/security/verifyReset.cfm
Add cbcsrf to the admin reset password page
> CONTENTBOX-1204 #TESTING

- modules/contentbox/modules/contentbox-admin/modules/contentbox-security/handlers/security.cfc
- modules/contentbox/modules/contentbox-admin/modules/contentbox-security/views/security/lostPassword.cfm
Add cbCSRF to admin forget password page
> CONTENTBOX-1203 #testing

- modules/contentbox/models/modules/ModuleService.cfc
- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
Fixes an issue where an error was thrown when an orphaned module was detected.
> Resolves an error thrown because `module` is not defined

- modules/contentbox/models/modules/ModuleService.cfc
- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
Fixes an additional undefined reference which was throwing an error
> Fix undefined `module` reference

- modules/contentbox/models/content/PageService.cfc
- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
- modules/contentbox/modules/contentbox-admin/handlers/sites.cfc
- modules/contentbox/modules/contentbox-admin/views/sites/editor.cfm
- Allows Projection List to be passed in to speed up Site config load times
> Resolves CONTENTBOX-1279

- modules/contentbox/models/content/renderers/WidgetRenderer.cfc
- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
Allows more usable information in the UI for easy debugging of widget rendering errors.
> Add additional information for UI widget debugging

- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
- modules/contentbox/modules/contentbox-admin/views/menus/editor.cfm
- workbench/resources/scss/theme/_main-content.scss
> Contentbox 1168 responsive UI verifications #testing

- modules/contentbox/models/exporters/ContentBoxExporter.cfc
- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
Resolves errors thrown when attempting to export a site bundle
> Updates DSL and adds Current Site Arg to getAllForExport

- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
- modules/contentbox/modules/contentbox-api/modules/contentbox-api-v1/handlers/entries.cfc
Rename tags in order to get inside the folders
> Rename tags #testing

- modules/contentbox/models/security/twofactor/TwoFactorService.cfc
- modules/contentbox/modules/contentbox-admin/includes/js/contentbox-app.js
- workbench/resources/js/contentList.js
Redo PR 490 - ensure the source file is modified for future packing
I was unable to run Grunt, locally, so the packed min files will need to be pushed.    The dependency `rochappy/Bootstrap-Confirmation` is no longer available on GitHub and will need to be replaced in the `package.json` and `yarn.lock` files
> Patch/Redo PR 490

- modules/contentbox/migrations/2022_03_07_155812_v5.1.0_page_sslonly_removals.cfc
- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/seeders/BaseSeeder.cfc
delete the transaction sentence
> delete the transaction

- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/modules/contentbox-admin/handlers/permissionGroups.cfc
- modules/contentbox/modules/contentbox-admin/handlers/roles.cfc
- modules/contentbox/seeders/BaseSeeder.cfc
I updated the remove method of  roles and group permissions to remove multiple records
> I updated the remove method of  roles and group permissions

- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/models/security/SecurityService.cfc
- modules/contentbox/seeders/BaseSeeder.cfc
getName() does not exist in the Author entity.
it was replaced by `getFullName()`
> Fix issue when resetting an user password

- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/models/system/CBHelper.cfc
- modules/contentbox/modules/contentbox-admin/views/_components/editor/sidebar/Modifiers.cfm
- modules/contentbox/seeders/BaseSeeder.cfc
- tests/specs/contentbox-web/contentbox/unit/system/CBHelperTest.cfc
Am also defaulting the value to NULL in case a parentContent was assigned before this was fixed.
> CONTENTBOX-1416 Added logic to not display parent section for an entry

- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/modules/contentbox-admin/views/menus/providers/content/adminHelper.cfm
Resolves the unresponsive modal call when the user clicks on the "Select Content Item" button.
> CONTENTBOX-1445 Menu Manager Create New Content Item Fix

- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/modules/contentbox-admin/layouts/admin.cfm
- modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_sidebars.scss
- modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_variables.scss
- modules/contentbox/modules/contentbox-admin/views/_components/ui/CBIcon.cfm
Moved the Menu toggle from the header to the sidebar area.
> Contentbox 1469 improve position of menu toggle

- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/models/menu/providers/ContentProvider.cfc
- modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_nestable-sortable.scss
- modules/contentbox/modules/contentbox-admin/views/menus/provider.cfm
> Corrected color and icon.

- modules/contentbox/models/comments/CommentService.cfc
- modules/contentbox/models/menu/item/ContentMenuItem.cfc
- modules/contentbox/models/menu/providers/ContentProvider.cfc
- modules/contentbox/modules/contentbox-admin/handlers/menus.cfc
This resolves the issue of the missing preview, of a menu in the Menu manager.
> Contentbox 1484 menu preview error

- modules/contentbox/modules/contentbox-admin/views/settings/sections/siteOptions.cfm
Fix missing fieldset tag and improve code indenting
> CONTENTBOX-1498 #resolve

- box.json
- changelog.md
- modules/contentbox/migrations/2023_12_12_164002_EditorsCanClearCaches.cfc
Content
CONTENTBOX-1500
Please delete options that are not relevant.
> Defensive Coding for Permissions Migration

- modules/contentbox/models/security/SecurityValidator.cfc
fix deprecation warning
Please include a summary of the changes and which issue(s) is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
**Please note that all PRs must have tests attached to them**
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
All PRs must have an accompanied Jira issue. Please make sure you created it and linked it here.
> Bug Tracker: https://ortussolutions.atlassian.net/jira/software/c/projects/COLDBOX/issues
Please delete options that are not relevant.
- [] I have commented my code, particularly in hard-to-understand areas
> CONTENTBOX-1517 Update SecurityValidator.cfc
