Ortus-Solutions/ContentBox

modules/contentbox-admin/views/entries/editor.cfm
The floated button start to float at the last line-position of the element immediately before it. Change the position will center it.
=> Center floated button on panel title

modules/contentbox/models/ui/ThemeService.cfc
The default theme has a Theme.cfc descripor path, on a shared hosting it cannot be found and throws error.
=> Uppercase error on ubuntu

modules/contentbox-admin/handlers/contentStore.cfc
fixes a bug at least for MSSQL 2008
=> rc.parentContent can be empty string

workbench/resources/express/bin/setclasspath.bat
currently the JRE_HOME is set regardless of whether it exists (Express with JRE) or not (Express without JRE), making the no-JRE version unusable as it overwrites the JRE_HOME variable if set properly in the Environment.  I suspect that the *nix version .sh suffers from the same issue, but have not checked that as of yet.
=> set JRE_HOME only if it exists

modules/contentbox-ui/handlers/media.cfc
I had an issue with images paths containing spaces. When logging, I found the app was looking for a file-system path containing `%20` in it, causing it to fail.
This change url decodes the path before doing all the other transformations.
=> URL decode the file path to prevent issues with spaces, etc.

modules/contentbox-admin/handlers/contentStore.cfc
I took the slug logic from the pages.cfc handler and applied it here.  This now seems to update the ContentStore slug value properly.
=> Fix for CONTENTBOX-774: Slug generate a loop of parent slug in ContentStore

modules/contentbox-admin/handlers/ckfilebrowser.cfc
Using the `event.getPrivateValue( "cbCKfileBrowserDefaultEvent", "contentbox-filebrowser:home.index" )`  allows this setting to be overridden upstream by an interceptor.  
This is necessary if you simply want to intercept and replace the data used by the filebrowser rather than rewrite (and maintain) an entire filebrowser modue.
=> Allow `cbCKfileBrowserDefaultEvent` to be overridden

modules/contentbox/models/media/MediaService.cfc
When the Installer loads, the cb_media_directoryRoot setting does not exist.
This means the media service will error on module load of the filebrowser.
We need to default this, just in case it has not been created yet.
https://ortussolutions.atlassian.net/browse/CONTENTBOX-864
=> cb_media_directoryRoot needs a default

modules/contentbox/ModuleConfig.cfc
The `settingService` variable was not available in this method, which was causing the use of environment overrides to throw the error:
```
Message	variable [SETTINGSERVICE] doesn't exist
Stacktrace	The Error Occurred in
/app/modules/contentbox/ModuleConfig.cfc: line 194 
192: 
193: // Append and override
194: var allSettings = settingService.getAllSettings( asStruct = true );
```
=> Fixes missing variable exception

modules/contentbox/modules/contentbox-admin/modules/contentbox-ckeditor/ModuleConfig.cfc, modules/contentbox/modules/contentbox-admin/modules/contentbox-ckeditor/models/CKEditor.cfc
This allows easier inclusion of multiple css files for CKEditor ContentsCss.  Especially helps when multiple modules need to add css to CKEditor ContentsCss.
=> Added ContentsCss interceptor to CKEditor.cfc

modules/contentbox/modules/contentbox-ui/views/adminbar/index.cfm
I installed and ran contentbox with commandbox, and at some point when trying to see a preview I got an error 
> Type: Template
Messages: Invalid CFML construct found on line 8 at column 62. ColdFusion was looking at the following text:
=
Then I changed the operator "==" for "eq" I think that operator only works on Lucee
=> The operator == does not work in CF

modules/contentbox/modules/contentbox-admin/handlers/autoupdates.cfc
because it's Markdown und not parsed (sorry this is just a quick browser edit, so two patches)
=> Version info in dialog looks broken

modules/contentbox/modules/contentbox-admin/handlers/forgebox.cfc, modules/contentbox/modules/contentbox-admin/views/forgebox/index.cfm, modules/contentbox/modules/contentbox-admin/views/forgebox/indexHelper.cfm, workbench/devincludes/scss/theme/_pagination.scss
Currently there is no way to view more than the first 25 ContentBox modules causing some modules to be hidden from users.  This PR goes along with the PR I made for the ForgeBox SDK.
=> Added pagination to ForgeBox installer

modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/views/home/indexHelper.cfm
This allows for file paths that have two forward slashes to work when using the file browser quick view and download functions.  This fixes an issue when trying to use s3 to store media.
=> Use encodeURIComponent function instead of escape function

modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/handlers/Home.cfc, modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/views/home/index.cfm, modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/views/home/indexHelper.cfm
Currently, if you have a folder or file named "Events", it will be displayed very tall and with a green background.  This is because the id for the file or folder is "events" which is also an id of a ContentBox admin element and thus the styles from that element are applied unintentionally to the Events folder.  This PR prefixes the file and folder ids with "fb-file-" or "fb-dir-" to prevent this issue.
I have only noticed this with an Events folder but it has the potential to happen to any other folder that has an id which is styled by the ContentBox admin styles.
=> Media manager bug fixes

modules/contentbox/models/security/twofactor/ITwoFactorProvider.cfc, modules/contentbox/models/security/twofactor/TwoFactorService.cfc, modules/contentbox/modules/contentbox-admin/ModuleConfig.cfc, modules/contentbox/modules/contentbox-admin/handlers/authors.cfc, modules/contentbox/modules/contentbox-admin/interceptors/UnenrollTwoFactorOnProviderChange.cfc, modules/contentbox/modules/contentbox-admin/layouts/inc/HTMLHead.cfm, modules/contentbox/modules/contentbox-admin/layouts/simple.cfm, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/ModuleConfig.cfc, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/handlers/security.cfc, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/handlers/twofactor.cfc, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/interceptors/CheckForForceTwoFactorEnrollment.cfc, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/modules/contentbox-email-twofactor/models/EmailTwoFactorProvider.cfc, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/views/twofactor/index.cfm, modules/contentbox/modules/contentbox-admin/views/authors/editor/twoFactor.cfm, modules/contentbox/modules/contentbox-admin/views/settings/sections/loginOptions.cfm, modules/contentbox/modules/contentbox-admin/views/twofactor/forceEnrollment.cfm
This pull request improves on the two-factor enrollment flow.
1. Enrollment now requires entering a valid code before two-factor authentication is turned on.
2. If global two-factor authentication is on, users will still be able to configure their two-factor settings and enroll in the default provider.  They will not be able to access any other pages.
3. Providers can now specify an HTML form to present to the user to configure their profile.  This allows providers to collect the needed user information during forced enrollment.  This will default to the current values for the user, if any.
4. Changing the default provider unenrolls all currently enrolled users so they can enroll in the new two-factor authentication provider.
=> Improved Two-Factor Enrollment Flow

modules/contentbox/models/ui/ThemeService.cfc
thisSettingName doesn't exist, its KEY now.
https://ortussolutions.atlassian.net/browse/CONTENTBOX-989
=> ThemeService was erroring when saving settings

modules/contentbox/modules/contentbox-admin/views/tools/exporter.cfm
Fixed an error when clicking Tools --> Export in the admin (with CF11 on Ubuntu).
In export.cfm file for looping on widget query (it's a query object created using queryNew() function) cfloop is using. The error is due to the cfloop, so we replaced it from for() loop in cfscript. Here, is the link for more info https://gist.github.com/bennadel/2421037. After applying for() loop, tested the code in CF11, CF2016 and Lucee 5.2.6+60
Here is the ticket link for more error detail: https://ortussolutions.atlassian.net/browse/CONTENTBOX-775
=> Error clicking Tools --> Export in admin (In CF11)

modules/contentbox/models/system/CBHelper.cfc, modules/contentbox/models/ui/Paging.cfc
im wanting to get the bootstrap elements on the blog, but i dont want to interfere with any other use of the paging module.  this only affects when the 'aslist' paramenter is passed with the exception of the col-sm-6 to col-sm12 changes to allow for more room.  this could be changed back for compatibility.
=> blog paging bootstrap compatable

modules/contentbox-dsncreator/models/LuceeHelper.cfc
Check for `Local.dbPort` results in the `dsnString` and `dbPort` vars not being set when specifying custom port. 
Moved local port detection to occurr after the dbType selection, overwriting the default port.
=> Fix 'dsnString not found' when specifying port. (#1)

modules/contentbox/models/security/LoginTracker.cfc
Array.len is not supported in Lucee 4, instead, we need to use arrayLen(array)
=> Fixed Lucee 4 Login Issue.

modules/contentbox/modules/contentbox-admin/modules/contentbox-filebrowser/Gruntfile.js
Fix gruntfile causing the spacing in the FB Assets src
Related to https://ortussolutions.atlassian.net/browse/CONTENTBOX-1084
=> Fix gruntfile spacing in the FB Assets src

robots.txt
This seems to break a lot of things with google.
We need to think about the robots.txt and make it better for general users
=> Remove includes folder from Robots txt

modules/contentbox/models/system/Setting.cfc
Fixes #1085 
Ensures that the setting name ( slug ) is unique, and cannot be duplicated. 
Without this, if a weird cache race condition is found, the Preflight check would insert 135 duplicate settings, causing every ORM findWhere to return more than 1 record for a setting name, stopping ColdBox from Initiliazing, resulting in many strange and not so wonderful errors. 
https://ortussolutions.atlassian.net/browse/CONTENTBOX-1085
=> CONTENTBOX-1085

.env.template
Fixes an issue loading the Mysql driver, because ContentBox trying to use the v5 driver but specifying the v8 bundle name and class name.
This breaks the ContentBox DSN creator when installing a new site using `box install contentbox-installer`.
=> fix Mysql 5 driver class/bundle name settings

modules/contentbox/models/comments/Comment.cfc, modules/contentbox/models/content/BaseContent.cfc, modules/contentbox/models/content/Category.cfc, modules/contentbox/models/content/ContentVersion.cfc, modules/contentbox/models/content/CustomField.cfc, modules/contentbox/models/content/Stats.cfc, modules/contentbox/models/menu/Menu.cfc, modules/contentbox/models/menu/item/BaseMenuItem.cfc, modules/contentbox/models/modules/Module.cfc, modules/contentbox/models/security/Author.cfc, modules/contentbox/models/security/LoginAttempt.cfc, modules/contentbox/models/security/Permission.cfc, modules/contentbox/models/security/PermissionGroup.cfc, modules/contentbox/models/security/Role.cfc, modules/contentbox/models/security/SecurityRule.cfc, modules/contentbox/models/subscriptions/BaseSubscription.cfc, modules/contentbox/models/subscriptions/Subscriber.cfc, modules/contentbox/models/system/Setting.cfc, modules/contentbox/models/system/Site.cfc
Remove `setter=false` attributes on PKs to allow imports to use their own PK GUIDs.  `update=false` will still prevent population or override of PK values.
=> Feature - Enable Setters on Primary Keys

Application.cfc
I found this issue when I was trying the ContentBox FormBuilder. It was not clear to me as a new ContentBox user why the module wasn't working. In the end, it turned out that modules_user is not currently included in the ormSettings so some contentbox modules on forgebox don't work without Application.cfc being updated by the user.  It was fixed with the help of Michael Born during December'd Office Hours zoom call.
This change resolves the issue I raised. https://ortussolutions.atlassian.net/browse/CONTENTBOX-1453
=> add modules_user to ORM settings

modules/contentbox/models/comments/CommentService.cfc, modules/contentbox/modules/contentbox-admin/layouts/admin.cfm, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/views/security/login.cfm, modules/contentbox/modules/contentbox-admin/modules/contentbox-security/views/security/lostPassword.cfm, modules/contentbox/modules/contentbox-admin/resources/assets/sass/contentbox.scss, modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_base.scss, modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_header.scss, modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_main-content.scss, modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_sidebars.scss, modules/contentbox/modules/contentbox-admin/resources/assets/sass/theme/_variables.scss, modules/contentbox/widgets/EntryInclude.cfc, modules/contentbox/widgets/Menu.cfc, modules/contentbox/widgets/PageInclude.cfc
I updated the color palette to have the following key swatches:
Since the sidebar toggle overlapped one of the menu headings, in mobile view, I moved the toggle to the left of the logo, which is more standard.
I did not completely revert the sidebar since there was not enough contrast between the subnav text and its background.  I did however darkened the active and hover states, to use the updated palette.  Compared to the original subnavigation, I lightened the background color.  I kept the subnav bullets but I darkened them.
Hovering over another menu item:
I updated the Login page to have a simpler and cleaner look:
=> Sidebar style updates

modules/contentbox/models/menu/providers/MediaProvider.cfc, modules/contentbox/modules/contentbox-admin/views/menus/providers/media/admin.cfm, modules/contentbox/modules/contentbox-admin/views/settings/sections/siteOptions.cfm, modules/contentbox/modules/contentbox-admin/views/tools/exporter.cfm
Restored the Media icon in the Menu Designer page:
=> Missing media icons

modules/contentbox/models/security/RateLimiter.cfc
RateLimiter stores request data in variables scope. Entries are never purged, if site gets many request, can lead to memory/performance issues
This fix is not tested (mentioned to Luis), since we are on older version
CONTENTBOX-1512
Please delete options that are not relevant.
=> Update RateLimiter.cfc, fix for CONTENTBOX-1512

modules/contentbox/models/system/SettingService.cfc
I created a new variable to increase the scope of site ID variable, in the bulkSave method.
With that, we prevent that the Global HTML option doesn't create a new record and update it instead
> Bug Tracker: https://ortussolutions.atlassian.net/browse/CONTENTBOX-1511
- [ x ] Bug Fix
=> Resolve CONTENTBOX-1511

modules/contentbox/migrations/init/create_author.cfc, modules/contentbox/migrations/init/create_category.cfc, modules/contentbox/migrations/init/create_comments.cfc, modules/contentbox/migrations/init/create_menu_items.cfc, modules/contentbox/migrations/init/create_modules.cfc, modules/contentbox/migrations/init/create_security_rules.cfc, modules/contentbox/migrations/init/create_settings.cfc, modules/contentbox/migrations/init/create_sites.cfc, modules/contentbox/migrations/init/create_stats.cfc, modules/contentbox/migrations/init/create_subscribers.cfc, modules/contentbox/migrations/init/create_subscriptions.cfc
add table name to index
https://ortussolutions.atlassian.net/browse/CONTENTBOX-1524
**Please note that all PRs must have tests attached to them**
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
All PRs must have an accompanied Jira issue. Please make sure you created it and linked it here.
> Bug Tracker: https://ortussolutions.atlassian.net/jira/software/c/projects/COLDBOX/issues
Please delete options that are not relevant.
- [ x] New and existing unit tests pass locally with my changes
=> CONTENTBOX-1524 index names have to be unique with postgres, so rename idx_deleted
